import { AppMetadata, ActivityItem, User } from './types';
import { 
  Database as DatabaseIcon, 
  Table as TableIcon, 
  Globe, 
  Zap 
} from 'lucide-react';

export const AI_AGENTS: AppMetadata[] = [
  {
    id: 'agent-1',
    name: 'ContentCraft AI',
    type: 'AI Agent',
    category: 'Marketing & Content',
    description: 'Generates SEO blog posts, social captions, and ad copy using GPT-4o. Pulls topics from Airtable, publishes to Notion and WordPress automatically.',
    status: 'Running',
    lastRun: '3 min ago',
    totalRuns: 8432,
    successRate: 97.2,
    avgDuration: '4.1s',
    costPerRun: '$0.034',
    totalCost: '$142.80',
    nodes: ['GPT-4o', 'Airtable', 'Notion', 'WordPress Webhook'],
    tags: ['Marketing', 'Content', 'SEO'],
    created: 'Jan 12, 2025',
    owner: 'Sarah Mitchell'
  },
  {
    id: 'agent-2',
    name: 'LeadHunter Pro',
    type: 'AI Agent',
    category: 'Sales & CRM',
    description: 'Scrapes LinkedIn and Apollo for leads, enriches with Clearbit data, scores with AI, and pushes qualified leads into HubSpot CRM automatically.',
    status: 'Idle',
    lastRun: '2h ago',
    totalRuns: 3218,
    successRate: 91.4,
    avgDuration: '8.7s',
    costPerRun: '$0.12',
    totalCost: '$386.16',
    nodes: ['Web Scraper', 'Clearbit', 'Claude 3.5', 'HubSpot'],
    tags: ['Sales', 'CRM', 'Leads'],
    created: 'Feb 3, 2025',
    owner: 'James Okafor'
  },
  {
    id: 'agent-3',
    name: 'BugPatrol',
    type: 'AI Agent',
    category: 'Engineering & Dev',
    description: 'Monitors GitHub PRs, runs AI code review using Claude 3.5, posts inline comments, assigns reviewers, and creates Linear issues for critical bugs.',
    status: 'Error',
    lastRun: '45 min ago',
    totalRuns: 12041,
    successRate: 88.6,
    avgDuration: '6.2s',
    costPerRun: '$0.08',
    totalCost: '$963.28',
    nodes: ['GitHub Webhook', 'Claude 3.5', 'Linear', 'Slack'],
    tags: ['Engineering', 'Code Review', 'GitHub'],
    created: 'Nov 28, 2024',
    owner: 'Priya Nambiar',
    error: 'GitHub API rate limit exceeded — retry in 12m'
  },
  {
    id: 'agent-4',
    name: 'FinanceRadar',
    type: 'AI Agent',
    category: 'Finance & Payments',
    description: 'Pulls Stripe revenue data daily, generates P&L summaries with GPT-4o, detects anomalies, and sends Slack alerts when spending exceeds thresholds.',
    status: 'Paused',
    lastRun: '1d ago',
    totalRuns: 1876,
    successRate: 99.1,
    avgDuration: '3.4s',
    costPerRun: '$0.021',
    totalCost: '$39.40',
    nodes: ['Stripe', 'GPT-4o', 'Anomaly Detector', 'Slack'],
    tags: ['Finance', 'Stripe', 'Alerts'],
    created: 'Mar 1, 2025',
    owner: 'Alex Johnson',
    pausedReason: 'Stripe API key rotation in progress'
  },
  {
    id: 'agent-5',
    name: 'TalentScout',
    type: 'AI Agent',
    category: 'HR & Operations',
    description: 'Screens resumes from Greenhouse ATS using Claude 3.5, scores candidates against job requirements, sends personalized rejection/interview emails via Resend.',
    status: 'Idle',
    lastRun: '6h ago',
    totalRuns: 2654,
    successRate: 94.8,
    avgDuration: '5.9s',
    costPerRun: '$0.045',
    totalCost: '$119.43',
    nodes: ['Greenhouse', 'Claude 3.5', 'Scorer', 'Resend'],
    tags: ['HR', 'Recruiting', 'Automation'],
    created: 'Feb 19, 2025',
    owner: 'Marcus Webb'
  }
];

export const TOOLS: AppMetadata[] = [
  {
    id: 'tool-1',
    name: 'SEO Keyword Extractor',
    type: 'Tool',
    category: 'Marketing & Content',
    description: 'Paste any URL or text — extracts top SEO keywords, search volume estimates, and competitor gap analysis using Serper API + GPT-4o.',
    status: 'Idle',
    lastRun: '30 min ago',
    totalRuns: 5102,
    successRate: 98.3,
    avgDuration: '2.8s',
    costPerRun: '$0.018',
    input: 'URL or raw text',
    output: 'JSON keyword list + scores',
    tags: ['Marketing', 'SEO', 'Research'],
    created: 'Jan 15, 2025',
    owner: 'Sarah Mitchell'
  },
  {
    id: 'tool-2',
    name: 'Invoice Generator',
    type: 'Tool',
    category: 'Finance & Payments',
    description: 'Takes client name, line items, and rates — generates branded PDF invoices via PDF Generator node and sends via Resend. Logs to Google Sheets automatically.',
    status: 'Running',
    lastRun: '8 min ago',
    totalRuns: 1340,
    successRate: 99.7,
    avgDuration: '1.9s',
    costPerRun: '$0.009',
    input: 'Form (client, items, amounts)',
    output: 'PDF + email confirmation',
    tags: ['Finance', 'Invoicing', 'PDF'],
    created: 'Feb 1, 2025',
    owner: 'Alex Johnson'
  },
  {
    id: 'tool-3',
    name: 'Code Explainer',
    type: 'Tool',
    category: 'Engineering & Dev',
    description: 'Paste any code snippet — Claude 3.5 explains it line by line, identifies bugs, suggests improvements, and generates unit tests automatically.',
    status: 'Idle',
    lastRun: '1h ago',
    totalRuns: 9871,
    successRate: 96.1,
    avgDuration: '3.3s',
    costPerRun: '$0.027',
    input: 'Code snippet (any language)',
    output: 'Explanation + suggestions + tests',
    tags: ['Engineering', 'Code', 'AI'],
    created: 'Nov 15, 2024',
    owner: 'Priya Nambiar'
  },
  {
    id: 'tool-4',
    name: 'Meeting Summarizer',
    type: 'Tool',
    category: 'HR & Operations',
    description: 'Upload any meeting transcript or audio — Whisper transcribes, GPT-4o extracts action items, decisions, and owners, then posts summary to Notion.',
    status: 'Paused',
    lastRun: '3d ago',
    totalRuns: 788,
    successRate: 93.4,
    avgDuration: '12.1s',
    costPerRun: '$0.061',
    input: 'Audio file or transcript text',
    output: 'Structured summary in Notion',
    tags: ['HR', 'Meetings', 'Productivity'],
    pausedReason: 'Notion integration needs re-auth',
    created: 'Mar 5, 2025',
    owner: 'Marcus Webb'
  },
  {
    id: 'tool-5',
    name: 'Market Research Bot',
    type: 'Tool',
    category: 'Research & Data',
    description: 'Enter any company or topic — scrapes web, pulls news via RSS, summarizes competitor landscape using Claude 3.5, exports to Google Docs.',
    status: 'Error',
    lastRun: '2h ago',
    totalRuns: 2203,
    successRate: 85.2,
    avgDuration: '18.4s',
    costPerRun: '$0.094',
    input: 'Company name or research topic',
    output: 'Research report in Google Docs',
    tags: ['Research', 'Competitive Intel', 'Docs'],
    error: 'Web Scraper timeout — target site blocked',
    created: 'Feb 10, 2025',
    owner: 'Sarah Mitchell'
  }
];

export const APPS: AppMetadata[] = [
  {
    id: 'app-1',
    name: 'SalesDesk CRM',
    type: 'App',
    category: 'Sales & CRM',
    description: 'Full internal CRM built on NodeBuilder. Displays leads from HubSpot, tracks pipeline stages, shows revenue charts, and lets reps trigger follow-up email sequences directly from the dashboard.',
    status: 'Running',
    lastRun: '1 min ago',
    totalRuns: 24310,
    successRate: 99.2,
    avgDuration: '0.8s',
    costPerRun: '$0.004',
    totalCost: '$97.24',
    uiComponents: ['KPI bar', 'pipeline table', 'revenue chart', 'contact cards', 'email trigger button'],
    dataBoundTo: 'HubSpot → LeadHunter Pro output',
    tags: ['Sales', 'CRM', 'Dashboard'],
    created: 'Jan 5, 2025',
    owner: 'James Okafor'
  },
  {
    id: 'app-2',
    name: 'Content Calendar',
    type: 'App',
    category: 'Marketing & Content',
    description: 'Visual content planning dashboard. Shows scheduled posts by channel (LinkedIn, Twitter, Blog), lets team approve AI-generated drafts, and one-click publishes via ContentCraft AI agent.',
    status: 'Idle',
    lastRun: '4h ago',
    totalRuns: 6782,
    successRate: 96.8,
    avgDuration: '1.2s',
    costPerRun: '$0.006',
    totalCost: '$40.69',
    uiComponents: ['Calendar view', 'channel filter', 'draft preview panel', 'approve/reject buttons'],
    dataBoundTo: 'ContentCraft AI → Airtable',
    tags: ['Marketing', 'Content', 'Calendar'],
    created: 'Feb 8, 2025',
    owner: 'Sarah Mitchell'
  },
  {
    id: 'app-3',
    name: 'DevOps Monitor',
    type: 'App',
    category: 'Engineering & Dev',
    description: 'Real-time engineering dashboard showing GitHub PR status, Linear sprint progress, deployment health on Vercel, and error rates from Sentry.',
    status: 'Running',
    lastRun: '30s ago',
    totalRuns: 41002,
    successRate: 98.9,
    avgDuration: '0.6s',
    costPerRun: '$0.002',
    totalCost: '$82.00',
    uiComponents: ['PR list', 'sprint board', 'deployment status cards', 'error feed', 'uptime chart'],
    dataBoundTo: 'GitHub + Linear + Vercel + Sentry',
    tags: ['Engineering', 'DevOps', 'Monitoring'],
    created: 'Dec 14, 2024',
    owner: 'Priya Nambiar'
  },
  {
    id: 'app-4',
    name: 'Finance Overview',
    type: 'App',
    category: 'Finance & Payments',
    description: 'Live financial dashboard pulling Stripe MRR, Plaid bank balances, and expense data. Shows P&L summary, revenue trends, and AI-generated anomaly alerts from FinanceRadar agent.',
    status: 'Paused',
    lastRun: '1d ago',
    totalRuns: 3441,
    successRate: 99.4,
    avgDuration: '1.1s',
    costPerRun: '$0.005',
    totalCost: '$17.21',
    uiComponents: ['MRR card', 'bank balance cards', 'P&L table', 'revenue line chart', 'alert feed'],
    dataBoundTo: 'Stripe + Plaid + FinanceRadar',
    tags: ['Finance', 'Revenue', 'Analytics'],
    created: 'Mar 2, 2025',
    owner: 'Alex Johnson'
  },
  {
    id: 'app-5',
    name: 'HR Portal',
    type: 'App',
    category: 'HR & Operations',
    description: 'Internal HR tool for the recruiting team. Shows open roles from Greenhouse, candidate pipeline, interview schedules from Google Calendar, and auto-generated candidate scorecards from TalentScout.',
    status: 'Idle',
    lastRun: '5h ago',
    totalRuns: 1892,
    successRate: 95.1,
    avgDuration: '1.4s',
    costPerRun: '$0.007',
    totalCost: '$13.24',
    uiComponents: ['Roles table', 'candidate kanban', 'calendar widget', 'scorecard viewer', 'email trigger'],
    dataBoundTo: 'Greenhouse + TalentScout + Resend',
    tags: ['HR', 'Recruiting', 'Internal Tool'],
    created: 'Feb 22, 2025',
    owner: 'Marcus Webb'
  }
];

export const WORKFLOWS: AppMetadata[] = [
  {
    id: 'workflow-1',
    name: 'Blog Post Pipeline',
    type: 'Workflow',
    category: 'Marketing & Content',
    description: 'End-to-end content workflow. Pulls weekly topics from Airtable → GPT-4o writes draft → Grammarly API edits → human review step → auto-publishes to WordPress + posts teaser to LinkedIn.',
    status: 'Running',
    lastRun: '12 min ago',
    totalRuns: 1204,
    successRate: 96.4,
    avgDuration: '22.3s',
    costPerRun: '$0.18',
    totalCost: '$216.72',
    nodeList: ['Schedule Trigger', 'Airtable', 'GPT-4o', 'Grammarly API', 'IF/Else (approved?)', 'WordPress', 'LinkedIn', 'Slack Notify'],
    tags: ['Marketing', 'Content', 'Publishing'],
    created: 'Jan 20, 2025',
    owner: 'Sarah Mitchell'
  },
  {
    id: 'workflow-2',
    name: 'Lead Nurture Sequence',
    type: 'Workflow',
    category: 'Sales & CRM',
    description: 'Triggered when new lead enters HubSpot. AI scores lead → routes hot leads to sales Slack → sends personalized 3-email drip via SendGrid → logs all activity back to HubSpot timeline.',
    status: 'Idle',
    lastRun: '1h ago',
    totalRuns: 4871,
    successRate: 93.7,
    avgDuration: '6.8s',
    costPerRun: '$0.041',
    totalCost: '$199.71',
    nodeList: ['HubSpot Trigger', 'Claude 3.5 Scorer', 'Switch (hot/warm/cold)', 'Slack Alert', 'SendGrid Email 1', 'Wait (3d)', 'SendGrid Email 2'],
    tags: ['Sales', 'Email', 'Automation'],
    created: 'Feb 10, 2025',
    owner: 'James Okafor'
  },
  {
    id: 'workflow-3',
    name: 'CI/CD Alert System',
    type: 'Workflow',
    category: 'Engineering & Dev',
    description: 'Listens to GitHub Actions webhooks. On failure → Claude 3.5 analyzes error logs → creates Linear issue → assigns to on-call engineer → posts detailed Slack alert with fix suggestions.',
    status: 'Error',
    lastRun: '20 min ago',
    totalRuns: 7632,
    successRate: 90.2,
    avgDuration: '4.4s',
    costPerRun: '$0.033',
    totalCost: '$251.86',
    nodeList: ['GitHub Webhook', 'Log Parser', 'Claude 3.5', 'Linear', 'Slack', 'PagerDuty'],
    tags: ['Engineering', 'CI/CD', 'Alerts'],
    created: 'Dec 1, 2024',
    owner: 'Priya Nambiar',
    error: 'PagerDuty webhook returning 401 — check API key'
  },
  {
    id: 'workflow-4',
    name: 'Monthly Expense Report',
    type: 'Workflow',
    category: 'Finance & Payments',
    description: 'Runs on the 1st of each month. Pulls all Stripe charges + Plaid transactions → categorizes with GPT-4o → generates PDF report → emails CFO via Resend → logs summary to Google Sheets.',
    status: 'Idle',
    lastRun: '28d ago',
    totalRuns: 14,
    successRate: 100,
    avgDuration: '34.2s',
    costPerRun: '$0.22',
    totalCost: '$3.08',
    nodeList: ['Schedule (1st monthly)', 'Stripe', 'Plaid', 'GPT-4o Categorizer', 'PDF Generator', 'Resend', 'Google Sheets'],
    tags: ['Finance', 'Reporting', 'Monthly'],
    created: 'Jan 1, 2025',
    owner: 'Alex Johnson'
  },
  {
    id: 'workflow-5',
    name: 'Employee Onboarding',
    type: 'Workflow',
    category: 'HR & Operations',
    description: 'Triggered when new hire is added in Greenhouse. Creates Notion onboarding page → sends welcome email via Resend → schedules intro meetings in Google Calendar → adds to Slack workspace channels.',
    status: 'Paused',
    lastRun: '5d ago',
    totalRuns: 43,
    successRate: 97.7,
    avgDuration: '8.1s',
    costPerRun: '$0.038',
    totalCost: '$1.63',
    nodeList: ['Greenhouse Trigger', 'Notion Create', 'Resend Welcome Email', 'Google Calendar', 'Slack Invite', 'Linear Onboarding Task', 'Notify HR'],
    tags: ['HR', 'Onboarding', 'Automation'],
    created: 'Feb 28, 2025',
    owner: 'Marcus Webb',
    pausedReason: 'Google Calendar OAuth token expired'
  }
];

export const MOCK_USERS: User[] = [
  { name: 'Alex Johnson', role: 'Admin', email: 'alex@nodebuilder.ai' },
  { name: 'Sarah Mitchell', role: 'Marketing', email: 'sarah@nodebuilder.ai' },
  { name: 'James Okafor', role: 'Sales', email: 'james@nodebuilder.ai' },
  { name: 'Priya Nambiar', role: 'Engineering', email: 'priya@nodebuilder.ai' },
  { name: 'Marcus Webb', role: 'HR', email: 'marcus@nodebuilder.ai' }
];

export const ANALYTICS = {
  stats: {
    totalRuns: { value: '124,309', change: '+12.5%', trend: 'up' },
    successRate: { value: '94.2%', change: '+0.4%', trend: 'up' },
    avgLatency: { value: '5.8s', change: '-150ms', trend: 'down' },
    totalCost: { value: '$2,341.80', change: '+5.2%', trend: 'up' },
  },
  runHistory: [
    { day: 'Mon', runs: 30 },
    { day: 'Tue', runs: 45 },
    { day: 'Wed', runs: 35 },
    { day: 'Thu', runs: 60 },
    { day: 'Fri', runs: 55 },
    { day: 'Sat', runs: 80 },
    { day: 'Sun', runs: 75 },
    { day: 'Mon', runs: 90 },
    { day: 'Tue', runs: 85 },
    { day: 'Wed', runs: 100 },
  ],
  healthDistribution: {
    success: 117100,
    failed: 7209,
    timeout: 0,
  },
  appPerformance: [
    { name: 'ContentCraft AI', runs: 8432, success: 97.2, latency: '4.1s', cost: '$142.80', status: 'healthy' },
    { name: 'LeadHunter Pro', runs: 3218, success: 91.4, latency: '8.7s', cost: '$386.16', status: 'healthy' },
    { name: 'BugPatrol', runs: 12041, success: 88.6, latency: '6.2s', cost: '$963.28', status: 'error' },
    { name: 'FinanceRadar', runs: 1876, success: 99.1, latency: '3.4s', cost: '$39.40', status: 'warning' },
    { name: 'SalesDesk CRM', runs: 24310, success: 99.2, latency: '0.8s', cost: '$97.24', status: 'healthy' },
  ],
  uptimeSLA: '99.9%',
  activeApps: 5,
  activeAgents: { running: 3, idle: 2 },
  errorsToday: 7,
  runsToday: 1842,
  runsThisWeek: 11204,
  topPerforming: { name: 'SalesDesk CRM', rate: '99.2%' },
  worstPerforming: { name: 'BugPatrol', rate: '88.6%' }
};

export const DATA_SOURCES = [
  { 
    id: 'ds-1', 
    name: 'Production DB', 
    type: 'PostgreSQL', 
    status: 'connected', 
    size: '1.2 GB', 
    lastSync: '2m ago', 
    icon: DatabaseIcon, 
    color: 'text-primary bg-primary-light',
    description: 'Main application database hosted on AWS RDS. Contains user profiles, app metadata, and run history.'
  },
  { 
    id: 'ds-2', 
    name: 'User Analytics', 
    type: 'MongoDB', 
    status: 'connected', 
    size: '450 MB', 
    lastSync: '15m ago', 
    icon: DatabaseIcon, 
    color: 'text-blue-500 bg-blue-500/10',
    description: 'Document store for granular user behavior events and clickstream data.'
  },
  { 
    id: 'ds-3', 
    name: 'Customer Sheets', 
    type: 'Google Sheets', 
    status: 'warning', 
    size: '12 MB', 
    lastSync: '1h ago', 
    icon: TableIcon, 
    color: 'text-success bg-success/10',
    description: 'Shared spreadsheet for manual lead entry and marketing campaign tracking.'
  },
  { 
    id: 'ds-4', 
    name: 'Marketing Assets', 
    type: 'AWS S3', 
    status: 'connected', 
    size: '24 GB', 
    lastSync: '1d ago', 
    icon: Globe, 
    color: 'text-orange-500 bg-orange-500/10',
    description: 'Object storage for generated images, PDF invoices, and meeting transcripts.'
  },
  { 
    id: 'ds-5', 
    name: 'Legacy CRM API', 
    type: 'REST API', 
    status: 'error', 
    size: '-', 
    lastSync: '3h ago', 
    icon: Zap, 
    color: 'text-error bg-error/10',
    description: 'Internal legacy CRM endpoint for syncing historical customer data.'
  },
  { 
    id: 'ds-6', 
    name: 'Realtime Cache', 
    type: 'Redis', 
    status: 'connected', 
    size: '128 MB', 
    lastSync: 'now', 
    icon: Zap, 
    color: 'text-red-500 bg-red-500/10',
    description: 'In-memory cache for session data and frequent API response buffering.'
  },
  { 
    id: 'ds-7', 
    name: 'Auth Database', 
    type: 'Supabase', 
    status: 'connected', 
    size: '85 MB', 
    lastSync: '5m ago', 
    icon: DatabaseIcon, 
    color: 'text-emerald-500 bg-emerald-500/10',
    description: 'Authentication and authorization store using Supabase Auth.'
  },
  { 
    id: 'ds-8', 
    name: 'Mobile Sync', 
    type: 'Firebase', 
    status: 'connected', 
    size: '2.1 GB', 
    lastSync: '10m ago', 
    icon: Zap, 
    color: 'text-yellow-500 bg-yellow-500/10',
    description: 'Real-time database for mobile app synchronization and push notifications.'
  },
];

export const VARIABLES = [
  { name: 'GEMINI_API_KEY', type: 'Secret', value: '••••••••••••••••', scope: 'Global', lastUsed: '2m ago', description: 'Primary API key for Google Gemini Pro models.' },
  { name: 'DB_PASSWORD', type: 'Secret', value: '••••••••••••••••', scope: 'Environment', lastUsed: '15m ago', description: 'Master password for the Production PostgreSQL database.' },
  { name: 'MAX_TOKENS', type: 'Number', value: '2048', scope: 'App Specific', lastUsed: '5m ago', description: 'Default token limit for AI Agent completions.' },
  { name: 'USER_ROLE', type: 'String', value: 'admin', scope: 'Session', lastUsed: 'now', description: 'Current session user role for permission checks.' },
  { name: 'ENABLE_LOGGING', type: 'Boolean', value: 'true', scope: 'Global', lastUsed: '1h ago', description: 'Toggle for verbose system-wide execution logs.' },
  { name: 'STRIPE_SECRET', type: 'Secret', value: '••••••••••••••••', scope: 'Global', lastUsed: '30m ago', description: 'Secret key for Stripe API integration (FinanceRadar).' },
  { name: 'AWS_REGION', type: 'String', value: 'us-east-1', scope: 'Environment', lastUsed: '1d ago', description: 'Target region for AWS S3 and RDS resources.' },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  { id: '1', appName: 'ContentCraft AI', action: 'Generated blog post', preview: 'Top 10 SaaS trends...', time: '2 min ago', status: 'success' },
  { id: '2', appName: 'LeadHunter Pro', action: 'Enriched 14 leads', preview: 'Apollo batch #4821', time: '8 min ago', status: 'success' },
  { id: '3', appName: 'BugPatrol', action: 'Code review failed', preview: 'PR #482 — rate limit', time: '45 min ago', status: 'failed' },
  { id: '4', appName: 'Invoice Generator', action: 'Generated PDF', preview: 'Acme Corp — $4,200', time: '1h ago', status: 'success' },
  { id: '5', appName: 'Blog Post Pipeline', action: 'Published to WordPress', preview: 'AI in 2025 — trends', time: '1h ago', status: 'success' },
  { id: '6', appName: 'FinanceRadar', action: 'Paused by user', preview: 'API key rotation', time: '2h ago', status: 'paused' },
  { id: '7', appName: 'SalesDesk CRM', action: 'Dashboard refreshed', preview: '42 leads updated', time: '2h ago', status: 'success' },
  { id: '8', appName: 'Market Research Bot', action: 'Scrape failed', preview: 'G2.com blocked request', time: '2h ago', status: 'failed' },
  { id: '9', appName: 'Lead Nurture Sequence', action: 'Sent email sequence', preview: 'james@acmecorp.com', time: '3h ago', status: 'success' },
  { id: '10', appName: 'DevOps Monitor', action: 'Deployment detected', preview: 'v2.4.1 — production', time: '4h ago', status: 'success' },
  { id: '11', appName: 'TalentScout', action: 'Screened 8 resumes', preview: 'Senior Engineer role', time: '6h ago', status: 'success' },
  { id: '12', appName: 'CI/CD Alert System', action: 'PagerDuty 401 error', preview: 'Build #1041 failed', time: '20 min ago', status: 'failed' }
];
